<center>
<h1><strong> Computer Vision assignment 2 </strong></h1>
</center>

**This assignment will challenge your understanding of basic python programming paradigm and evaluate your intution of numpy **

- Make sure all the implementations are general and should work for any test case that we use
- Numpy link: https://www.youtube.com/watch?v=QUT1VHiLmmI&t=958s 
- the above link will provide a general introduction to numpy - if additional information is needed refer to the documentation 



## **Instructions :**


- Make a copy of this Colab notebook (else any changes you make wont be saved)
- Feel free to add more code blocks in between questions if you feel you need it
- Submit the link of your Colab notebook on this [Link](https://forms.gle/ncuP2Xr5JhE6Hxcx9) once you are done with the assignment (Make sure to give edit access to BITS Pilani University)

---
## **Numpy**

In [31]:
import numpy as np
import string


#### `Q1) create a 1-D numpy array with elements from 0 to 10`

In [32]:
x=np.arange(11)
print('Array with elements from 0 to 10:',x)

Array with elements from 0 to 10: [ 0  1  2  3  4  5  6  7  8  9 10]



#### `Q2) Create a 2D numpy array of shape = (7,8)`

In [44]:
shape=(7,8)
a=np.ones(shape)
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


#### `Q3) Create a 1-D numpy array of size 10 with random integer values ranging from 40 to 69. Once created print the sorted array.`

In [69]:
a=np.random.randint(40,70,10)
a1=np.sort(a)
print(a1)

[40 48 51 59 60 61 64 64 67 69]


#### `Q4) Find indices of non-zero elements in [1,5,0,0,53,78,4,0,21,79,0,4,5,17]`

In [61]:
a=[1,5,0,0,53,78,4,0,21,79,0,4,5,17]
k=np.nonzero(a)
print(k)

(array([ 0,  1,  4,  5,  6,  8,  9, 11, 12, 13]),)



#### `Q5) Create a random vector and replce the maximum element by 10`

In [64]:
x=np.random.random(2)
print("Original Vector:",x)
x1=x.max()
x[x==x1]=10
print("Vector after replacing maximum element by 10:",x)

Original Vector: [0.54881394 0.87658711]
Vector after replacing maximum element by 10: [ 0.54881394 10.        ]
